services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "3010:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3011:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres01
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

